/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A configured pipeline. Build one and reuse it. */
export declare class Readback {
  constructor(options?: JsOptions | undefined | null)
  /** Runs the pipeline. Never throws for ordinary input. */
  check(input: JsCheckInput): JsVerdict
}

/**
 * Runs the Cleanup Guard alone: revert any edit that removed a protected
 * token, keep the rest of the polish.
 *
 * Useful when you want to sanitise an LLM rewrite without the rest of the
 * pipeline.
 */
export declare function checkCleanup(raw: string, cleaned: string, options?: JsOptions | undefined | null): JsGuardOutcome

/** Thresholds for one destination app. */
export interface JsAppPolicy {
  /** Pipe-separated app names, matched case-insensitively: `"Terminal|Cursor"`. */
  pattern: string
  /** Risk at or above this holds. Use a value above 1 to never hold. */
  hold: number
  /** Risk at or above this highlights. */
  highlight: number
}

/**
 * Everything the host application knows about one utterance.
 *
 * Only `text` is required. Each further field turns on another stage, so
 * adoption can be incremental.
 */
export interface JsCheckInput {
  /** The recogniser's output. */
  text: string
  /** Per-word confidence and timings. */
  words?: Array<JsWord>
  /** Competing transcriptions, from N-best or a second engine. */
  alternatives?: Array<string>
  /** Decoder-level signals. */
  signals?: JsSignals
  /** The LLM-polished rewrite. Supplying this turns on the Cleanup Guard. */
  cleaned?: string
  /** Voice-activity regions. Needs `words` with timings to be useful. */
  speech?: Array<JsSpeechRegion>
  /** Frontmost application, used to select a policy. */
  app?: string
  /** Terms to protect for this call only. */
  vocabulary?: Array<string>
}

/** One thing Readback wants the user to look at. */
export interface JsFlag {
  /** `"dropped_negation"`, `"changed_environment"`, `"low_confidence"`, … */
  kind: string
  /** `"critical"`, `"high"`, `"medium"`, `"low"` or `"none"`. */
  severity: string
  /** Byte offset into `text`, inclusive. */
  start: number
  /** Byte offset into `text`, exclusive. */
  end: number
  /** Safe to show in a tooltip. */
  evidence: string
  suggestion?: string
}

/** What the Cleanup Guard did on its own. */
export interface JsGuardOutcome {
  text: string
  reverted: boolean
  flags: Array<JsFlag>
}

/** Constructor options. */
export interface JsOptions {
  /** `"en"`, `"hinglish"`. Defaults to `["en"]`. */
  locales?: Array<string>
  /** Always-protected terms: names, projects, environments, jargon. */
  vocabulary?: Array<string>
  /** Use the built-in per-app routing: paranoid in terminals, relaxed in notes. */
  recommended?: boolean
  /** Per-app overrides, checked in order. First match wins. */
  apps?: Array<JsAppPolicy>
  /** Default hold threshold for apps with no rule. */
  hold?: number
  /** Default highlight threshold for apps with no rule. */
  highlight?: number
}

/** Which stages ran, for debugging a verdict. */
export interface JsProvenance {
  primaryProvider?: string
  cleanupGuardRan: boolean
  cleanupReverted: boolean
  omissionCheckRan: boolean
  scorer: string
}

/** Decoder-level signals, when the engine exposes them. */
export interface JsSignals {
  avgLogprob?: number
  noSpeechProb?: number
  compressionRatio?: number
}

/** A stretch of audio that voice-activity detection called speech. */
export interface JsSpeechRegion {
  startMs: number
  endMs: number
}

/** The answer. */
export interface JsVerdict {
  /** `"pass"`, `"highlight"` or `"hold"`. */
  action: string
  /** The text to insert, with any reverted spans already restored. */
  text: string
  flags: Array<JsFlag>
  risk: number
  stakes: number
  suspicion: number
  provenance: JsProvenance
}

/** One recognised word, with whatever the engine reported about it. */
export interface JsWord {
  text: string
  startMs?: number
  endMs?: number
  /** `0..1`. Omit when the engine does not report confidence. */
  confidence?: number
}

/** The crate version, so hosts can report what they loaded. */
export declare function version(): string
